# 应用服务 WEB 访问端口
server:
  port: 27915
# ----------------------------------------------------------------------------------------------------------------------
spring:
  mvc:
    # Springfox使用的路径匹配基于AntPathMatcher，而Spring Boot 2.6.X使用的是PathPatternMatcher
    pathmatch:
      matching-strategy: ant_path_matcher
# ----------------------------------------------------------------------------------------------------------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: honey0612
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
# ----------------------------------------------------------------------------------------------------------------------
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 2
        max-idle: 10
        max-active: 20
        max-wait: -1
# ----------------------------------------------------------------------------------------------------------------------
  mail:
    #配置 SMTP 服务器地址
    host: smtp.qq.com
    #SMTP 服务器的端口
    port: 465
    #配置邮箱用户名
    username: 2146321711@qq.com
    #配置密码，注意，不是真正的密码，而是刚刚申请到的授权码
    password: xcuvqwcuzhbmcjfd
    #默认的邮件编码
    default-encoding: UTF-8
    #配饰 SSL 加密工厂
    properties:
      mail:
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
        smtp:
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          socketFactory:
            port: 465
    protocol: smtp
  # ----------------------------------------------------------------------------------------------------------------------
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
rabbitmq:
  # 定义交换器
  exchange: exam-direct
  # --------------------------------------------------------------------------------------------------------------------
  # 定义考试创建的消息队列
  question-create: question-create-queue
  # 定义考试创建的路由键routing-key
  question-create-routing-key: question-create-queue-routing-key
  # --------------------------------------------------------------------------------------------------------------------
  # 定义一个审传递审核请求的消息队列
  review-request: log-review-request
  # 定义一个传递审核请求的路由键
  review-routing-key: log-review-requesi-routing-key
  # --------------------------------------------------------------------------------------------------------------------
  # 删除题库队列
  delete-question-bank: question-delete-queue
  # 删除队列路由键
  delete-question-bank-routing-key: question-delete-queue-routing-key
  # --------------------------------------------------------------------------------------------------------------------
  exam-create: exam-create-queue
  exam-create-routing-key: exam-create-queue-routing-key
  # --------------------------------------------------------------------------------------------------------------------
  exam-delete: exam-delete-queue
  exam-delete-routing-key: exam-delete-queue-routing-key
# ----------------------------------------------------------------------------------------------------------------------
mybatis:
  type-aliases-package: com.example.examsystem
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ----------------------------------------------------------------------------------------------------------------------